### ISSUE TITLE
Plugin not properly working

### ISSUE THREAD

**Issue by Marie-Rupprecht** [catalyst/moodle-report_coursesize#19] opened 2020-04-01 07:18 UTC
Hi :) I have just installed the plugin and was really happy at first because I got a nice list ranking my courses by size. However, when I click on "view stats" for any course, everything is displayed as "0 MB" (which can't be if I believe the general ranking). 
![grafik](https://user-images.githubusercontent.com/62940122/78109507-9c9ff100-73f9-11ea-9f8a-9692a01a52f7.png)
![grafik](https://user-images.githubusercontent.com/62940122/78109550-b2151b00-73f9-11ea-81fd-95e94d14db16.png)

Please help me! :)

**Comment by danmarsden** [comment] 2020-04-01 18:47
What Moodle version are you using and what Database type? postgres/mysql/MS sql/Oracle etc.

also - can you try setting debugging level to "Developer" and display errors  = on, then reload the page and let us know if any errors are being shown?

thanks,

**Comment by danmarsden** [comment] 2020-04-01 18:51
in fact - this looks like a duplicate of #11 - we've fixed that in the latest version and in the github branch here for Moodle 3.5 sites - if you're using 3.5 you might want to get the code from github here rather than the plugins db.
https://github.com/catalyst/moodle-report_coursesize/archive/MOODLE_35_STABLE.zip

**Comment by Marie-Rupprecht** [comment] 2020-04-02 06:02
Hi Dan, thanks for your quick reply! As I am not a developer, I am not sure I got the second part of your first comment. How can I set the debugging level to developer? 

We're using Moodle 3.5, so that might actually be a great tip. I try the github code then and let you know how it goes :)

**Comment by Marie-Rupprecht** [comment] 2020-04-03 12:53
Hi again, 

Unfortunately, I won't be able to use the code from you because of the policy of our Moodle provider. 
I managed to get Moodle to show any errors that are happening with the plugin and it didn't show anything at all. 

Do you have any other ideas what I could do to get the plugin to show me the details correctly? 
Thanks a lot!

**Comment by danmarsden** [comment] 2020-04-06 00:44
Hi Marie, 

You could try upgrading your Moodle to a newer relase like Moodle 3.8 or find another Moodle provider that is able to help you further - good luck!

**Closed by danmarsden** 2020-04-06 00:44 UTC

**Comment by Marie-Rupprecht** [comment] 2020-04-07 08:25
Hi Dan, 

okay - we're talking about an update for other reasons anyway...so I'll set this on hold until then :) 

Thank you!
